version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'localhost' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'  # Avoids port conflicts with host
        gitlab_rails['gitlab_shell_ssh_port'] = 2224  # Avoids host SSH port (22)
        nginx['listen_port'] = 80
    ports:
      - "8929:80"         
      - "2224:22"        

    volumes:
      - ~/apps/gitlab/config:/etc/gitlab
      - ~/apps/gitlab/logs:/var/log/gitlab
      - ~/apps/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-net
    privileged: true
    cap_add:
      - SYS_ADMIN

networks:
  gitlab-net:
    driver: bridge
