version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:7000'
        gitlab_rails['gitlab_shell_ssh_port'] = 7001
        prometheus['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitaly['cgroups_count'] = 0
    ports:
      - "7000:80"
      - "7001:22"
    volumes:
      - ~/apps/gitlab/config:/etc/gitlab
      - ~/apps/gitlab/logs:/var/log/gitlab
      - ~/apps/gitlab/data:/var/opt/gitlab
    
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB

