version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'localhost' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['listen_port'] = 80
    ports:
      - "8929:80"         
      - "2224:22"        

    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - gitlab-net
    privileged: true
    cap_add:
      - SYS_ADMIN

networks:
  gitlab-net:
    driver: bridge

volumes:
  gitlab-config:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/gitlab/config
      o: bind
  gitlab-logs:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/gitlab/logs
      o: bind
  gitlab-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/gitlab/data
      o: bind