services:
  # frontend app
  coder:
    image: coder:latest
    container_name: coder
    networks:
      - pm-cloud

  # TODO: add all services
  # main app logic
  app-logic:
    image: http-server:latest
    container_name: http_server
    # TODO: include all configs
    environment:
      - APP_ENV=production
      - APP_SECRET=test-secret
      - WS_PORT=6060
      - SECRET_KEY=
      - ACCESS_KEY=
      - S3_BUCKET=
      - S3_ENDPOINT=
      - S3_REGION=
      - RMQ_ADDR=rabbitmq
      - RMQ_USER=admin
      - RMQ_PASS=TestRab1234
      - RMQ_Q_NAME=jobs
      - DB_USER=test_user
      - DB_PASS=Sample1234Pass
      - DB_HOST=local_postgres_test
      - DB_NAME=pm_cloudify_db
      - DB_SSL_MODE=disable
    networks:
      - pm-cloud

  # postgresql (db)
  postgres:
    image: postgres:latest
    container_name: local_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: Sample1234Pass
      POSTGRES_DB: pm_cloudify_db
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pm-cloud

  #  ui app used to interact with db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=Sample1234Pass
  #   networks:
  #     - pm-cloud

  # rabbit mq (mb)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: test-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=TestRab1234
    networks:
      - pm-cloud
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # api gateway
  api-gateway:
    image: gateway:latest
    container_name: gateway
    ports:
      - "8080:80"
    networks:
      - pm-cloud-exposed
      - pm-cloud

# network config
networks:
  pm-cloud-exposed:
    driver: bridge

  pm-cloud:
    driver: bridge
    internal: true

# drivers
volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/postgres
      o: bind

  rabbitmq-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/rabbitmq
      o: bind
