services:
  coder:
    image: coder:latest
    container_name: coder
    networks:
      - pm-cloud
  postgres:
    image: postgres:latest
    container_name: local_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: Sample1234Pass
      POSTGRES_DB: pm_cloudify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pm-cloud
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_COOKIE=secret-cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=TestRab1234
    networks:
      - pm-cloud
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  app-logic:
    image: http-server:latest
    container_name: http_server
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "6060:80"
    environment:
      - APP_ENV=development
      - APP_SECRET=test-secret
      - WS_PORT=80
      - SECRET_KEY=
      - ACCESS_KEY=
      - S3_BUCKET=
      - S3_ENDPOINT=
      - S3_REGION=
      - RMQ_ADDR=rabbitmq
      - RMQ_USER=admin
      - RMQ_PASS=TestRab1234
      - RMQ_Q_NAME=jobs
      - DB_USER=test_user
      - DB_PASS=Sample1234Pass
      - DB_HOST=local_postgres_test
      - DB_NAME=pm_cloudify_db
      - DB_SSL_MODE=disable
    networks:
      - pm-cloud

  api-gateway:
    image: gateway:latest
    container_name: gateway
    depends_on:
      app-logic:
        condition: service_started
      coder:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      - pm-cloud
      - exposed-pm

networks:
  exposed-pm:
    driver: bridge

  pm-cloud:
    driver: bridge
    internal: true

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/postgres
      o: bind
  rabbitmq-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/rabbitmq
      o: bind
