services:
  db:
    image: postgres:latest
    container_name: local_postgres_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: Sample1234Pass
      POSTGRES_DB: pm_cloudify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ~/apps/postgres
      o: bind
