services:
  # postgresql core
  postgres:
    image: postgres:latest
    container_name: local_postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: Sample1234Pass
      POSTGRES_DB: pm_cloudify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net

  #  ui app used to interact with db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=Sample1234Pass
    networks:
      - postgres-net
    ports:
      - "9090:80"

networks:
  postgres-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: opt/apps/postgres
      o: bind
