version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: local_postgres_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: Sample1234Pass
      POSTGRES_DB: pm_cloudify_db
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
volumes:  
  postgres_data: